[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "byzfl"
version = "0.0.1"
description = "Acceleration methods for byzantine fl"
readme = "README.md"
requires-python = ">=3.8"

[tool.setuptools]
packages = ["byzfl"]
